title: Estelle Pan
#logo: 
description:   Hello there — welcome!  
  I'm Estelle, a data science/AI enthusiast.
  Outside of coding and analysis, you’ll find me behind a drum kit, practicing photojournalism, or lying in the grass with a random book.  

  This space is where I showcase the data science and AI projects I’m working on —  
  along with some of the photography I’ve taken, and maybe even a few drum performances
  Stay tuned :P

show_downloads: true 
theme: jekyll-theme-minimal 
